//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookSecurityAddInAnalysis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\git\\suspicious-box\\mail_templates\\pl\\legit.oft")]
        public string LegitTemplate {
            get {
                return ((string)(this["LegitTemplate"]));
            }
            set {
                this["LegitTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\git\\suspicious-box\\mail_templates\\pl\\spam.oft")]
        public string SpamTemplate {
            get {
                return ((string)(this["SpamTemplate"]));
            }
            set {
                this["SpamTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\git\\suspicious-box\\mail_templates\\pl\\malicious.oft")]
        public string MaliciousTemplate {
            get {
                return ((string)(this["MaliciousTemplate"]));
            }
            set {
                this["MaliciousTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\git\\suspicious-box\\mail_templates\\pl\\simulation.oft")]
        public string SimulationTemplate {
            get {
                return ((string)(this["SimulationTemplate"]));
            }
            set {
                this["SimulationTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\git\\suspicious-box\\mail_templates\\pl\\noattachment.oft")]
        public string NoAttachmentTemplate {
            get {
                return ((string)(this["NoAttachmentTemplate"]));
            }
            set {
                this["NoAttachmentTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("soc-pl@outlook.com")]
        public string SendFromMailbox {
            get {
                return ((string)(this["SendFromMailbox"]));
            }
            set {
                this["SendFromMailbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("suspicious-box@outlook.com")]
        public string RequestMailbox {
            get {
                return ((string)(this["RequestMailbox"]));
            }
            set {
                this["RequestMailbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Done")]
        public string RequestMailboxDoneFolder {
            get {
                return ((string)(this["RequestMailboxDoneFolder"]));
            }
            set {
                this["RequestMailboxDoneFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>received</string>
  <string>trace</string>
  <string>resent-date</string>
  <string>resent-from</string>
  <string>resent-sender</string>
  <string>resent-to</string>
  <string>resent-cc</string>
  <string>resent-bcc</string>
  <string>resent-msg-id</string>
  <string>orig-date</string>
  <string>from</string>
  <string>sender</string>
  <string>reply-to</string>
  <string>to</string>
  <string>cc</string>
  <string>bcc</string>
  <string>message-id</string>
  <string>in-reply-to</string>
  <string>references</string>
  <string>subject</string>
  <string>comments</string>
  <string>keywords</string>
  <string>optional-field</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HeaderWhitelist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HeaderWhitelist"]));
            }
            set {
                this["HeaderWhitelist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OutlookSecurityAddInAnalysisHeaderMail.msg")]
        public string TempMsgFileName {
            get {
                return ((string)(this["TempMsgFileName"]));
            }
            set {
                this["TempMsgFileName"] = value;
            }
        }
    }
}
