//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookSecurityAddInAnalysis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Marcin\\Dropbox\\study\\Specjalnościowa pracownia dyplomowa\\praca dyplomowa" +
            "\\mail_templates\\legit.oft")]
        public string LegitTemplate {
            get {
                return ((string)(this["LegitTemplate"]));
            }
            set {
                this["LegitTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Marcin\\Dropbox\\study\\Specjalnościowa pracownia dyplomowa\\praca dyplomowa" +
            "\\mail_templates\\spam.oft")]
        public string SpamTemplate {
            get {
                return ((string)(this["SpamTemplate"]));
            }
            set {
                this["SpamTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Marcin\\Dropbox\\study\\Specjalnościowa pracownia dyplomowa\\praca dyplomowa" +
            "\\mail_templates\\malicious.oft")]
        public string MaliciousTemplate {
            get {
                return ((string)(this["MaliciousTemplate"]));
            }
            set {
                this["MaliciousTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Marcin\\Dropbox\\study\\Specjalnościowa pracownia dyplomowa\\praca dyplomowa" +
            "\\mail_templates\\simulation.oft")]
        public string SimulationTemplate {
            get {
                return ((string)(this["SimulationTemplate"]));
            }
            set {
                this["SimulationTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Marcin\\Dropbox\\study\\Specjalnościowa pracownia dyplomowa\\praca dyplomowa" +
            "\\mail_templates\\noattachment.oft")]
        public string NoAttachmentTemplate {
            get {
                return ((string)(this["NoAttachmentTemplate"]));
            }
            set {
                this["NoAttachmentTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("soc-pl@outlook.com")]
        public string SendFromMailbox {
            get {
                return ((string)(this["SendFromMailbox"]));
            }
            set {
                this["SendFromMailbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("suspicious-box@outlook.com")]
        public string RequestMailbox {
            get {
                return ((string)(this["RequestMailbox"]));
            }
            set {
                this["RequestMailbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Done")]
        public string RequestMailboxDoneFolder {
            get {
                return ((string)(this["RequestMailboxDoneFolder"]));
            }
            set {
                this["RequestMailboxDoneFolder"] = value;
            }
        }
    }
}
